all:
  vars:
    ansible_connection: ssh
    ansible_user: ansible
    ansible_become: true
    ansible_ssh_private_key_file: ~/.ssh/ssh-key-infra_oci

    kafka_broker_custom_listeners:
          broker:
            name: INTERNAL
            port: 9091
            ssl_enabled: false
            ssl_mutual_auth_enabled: false
            sasl_protocol: none
          internal:
            name: EXTERNAL
            port: 9092
            ssl_enabled: false
            ssl_mutual_auth_enabled: false
            sasl_protocol: scram256
          client_listener:
            name: CLIENT
            port: 9093
            ssl_enabled: true
            ssl_mutual_auth_enabled: false
            sasl_protocol: plain

    #listener:
    #  name:
    #    external:
    #      scram-sha-256:
    #        sasl:
    #          jaas:
    #            config: "org.apache.kafka.common.security.scram.ScramLoginModule required username="admin" password="admin-secret""

    sasl_protocol: scram256
    ssl_enabled: false
    schema_registry_ssl_enabled: false
    jolokia_enabled: false
    jmxexporter_enabled: true
    confluent_server_enabled: false
    kafka_version: 3.0.0

    # Default users to Kafka. DO NOT CHANGE HERE!
    sasl_plain_users:
      admin:
        principal: 'kafka'
        password: 'admin-secret'
      schema_registry:
        principal: 'schema-registry'
        password: 'schema_registry-secret'
      kafka_connect:
        principal: 'kafka-connect'
        password: 'kafka_connect-secret'
      ksql:
        principal: 'ksqldb'
        password: 'ksql-secret'
      kafka_rest:
        principal: 'kafka_rest'
        password: 'kafka_rest-secret'
      graylog:
        principal: graylog
        password: graylog-secret
      control_center:
        principal: 'control-center'
        password: 'control_center-secret'
      kafka_connect_replicator:
        principal: 'kafka_connect_replicator'
        password: 'kafka_connect_replicator-secret'
      client:
        principal: 'client'
        password: 'client-secret'

zookeeper:
  hosts:
    172.31.49.20:
    172.31.49.27:
    172.31.49.98:
kafka_broker:
  hosts:
    172.31.49.20:
    172.31.49.27:
    172.31.49.98: